const JOB_STATUSES = {
  STARTING: 'STARTING',
  RUNNING: 'RUNNING',
  FINISHED_WITH_ERRORS: 'FINISHED_WITH_ERRORS',
  FINISHED_SUCCESSFULLY: 'FINISHED_SUCCESSFULLY',
  STALE: 'STALE'
};

// statuses that are considered active
JOB_STATUSES.ACTIVE_JOBS = [JOB_STATUSES.STARTING, JOB_STATUSES.RUNNING];

module.exports = JOB_STATUSES;
